NAME	= pipex

SRCS 	= srcs/pipex.c srcs/utils.c
OBJS 	= ${SRCS:.c=.o}
MAIN	= srcs/pipex.c

HEADER	= -Iincludes

CC 		= gcc
CFLAGS 	= -Wall -Wextra -Werror -g

.c.o:		%.o : %.c
	@gcc ${CFLAGS} ${HEADER} -c $< -o $(<:.c=.o)

all: 		${NAME}

${NAME}:	${OBJS}
	@make re -C ./libft
	@$(CC) ${OBJS} -Llibft -lft -o ${NAME}

clean:
	@make clean -C ./libft
	@rm -f ${OBJS}

fclean: 	clean
	@make fclean -C ./libft
	@rm -f $(NAME)
	@rm -f ${NAME}

re:			fclean all

.PHONY: all clean fclean re 
